### PR TITLE
Target Rider 2022.3.1

### PR DESCRIPTION
**Pull request by maartenba**

### CODE REVIEW

**Review by ForNeVeR — APPROVED** [review]

**Comment by ForNeVeR** [comment]
EAP 8 is known to be broken with gradle-intellij-plugin I think, so it should be okay to skip that EAP for now

**Comment by ForNeVeR** [comment]
Release SDK is known to be broken as well :(

**Comment by mfilippov** [comment]
But snapshot should be fixed. Yes?

**Comment by ForNeVeR** [comment]
It is, but a plugin built from SNAPSHOT SDK is not compatible with 2022.3.0. At least, by default.

**Comment by maartenba** [comment]
Building...

**Pull request merged**
