### PR TITLE
Fix RIDER-95452

### PR DESCRIPTION
**Pull request by rafaelldi**
`DebuggerHelperHost.getProcessArchitecture(lifetime, processId)` throws an exception on non-Windows platforms. I think we should change the method in the future (remove this exception) and I am not completely sure about the fix, but as a hot-fix it might be ok.

cc @ArseniiCherniaev 

https://youtrack.jetbrains.com/issue/RIDER-95452

### CODE REVIEW

**Comment by maartenba** [comment]
Can we use the current call on Windows and the alternative on Linux/macOS? Or does that make no sense?

**Review by maartenba — APPROVED** [review]

**Comment by rafaelldi** [comment]
Right now there is no alternative method for non-Windows platforms. But I think it is possible to remove this explicit exception from the method `DebuggerHelperHost.getProcessArchitecture(lifetime, processId)` (we need to test this).

**Comment by maartenba** [comment]
OK in that case - :shipit:

**Comment by ArseniiCherniaev** [comment]
Hey folks,

OS limitations are obsolete, it looks like we do not need them anymore. I'm going to remove checks, the fix will be merged in 232 soon.

**Comment by rafaelldi** [comment]
I think we should release this fix and return to this method `DebuggerHelperHost.getProcessArchitecture` in the next release.

**Comment by maartenba** [comment]
FYI I have updated this to use the original call on Windows, and use the new version on other OS. (fixes #710)

**Comment by rafaelldi** [comment]
@maartenba Thank you! Sorry I didn't understand your suggestion from the first time.

**Comment by maartenba** [comment]
I thought it was okay to keep your version, but apparently not in all cases (.net full framework) 😅

**Pull request merged**
