### PR TITLE
Improve build gradle script for the new version

### PR DESCRIPTION
**Pull request by rafaelldi**
Some changes for the build script. Tried to make it similar to the [script](https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/build.gradle.kts) from `intellij-platform-plugin-template` and from the [base repo](https://github.com/microsoft/azure-tools-for-java/blob/develop/PluginsAndFeatures/azure-toolkit-for-intellij/build.gradle).

### CODE REVIEW

**Comment by maartenba** [comment]
Have not tested it but seems OK at first glance 👍  (TeamCity thinks otherwise 😅 )

**Review by maartenba — APPROVED** [review]
Good idea to standardize the way other plugins do it.

**Comment by rafaelldi** [comment]
I think TeamCity isn't properly configured to build a new version of the plugin. By the way, what do you think about using [GitHub Actions](https://github.com/JetBrains/intellij-platform-plugin-template/tree/main/.github/workflows) to build the new version?

**Comment by maartenba** [comment]
We can do this indeed especially for the new plugin branch

**Pull request merged**
