### PR TITLE
IDEA-334617: Suggest installing Azure plugin for users who have Azure CLI installed

### PR DESCRIPTION
**Pull request by Flanker32**
Add executable dependency support to suggest plugin when azure cli is detected

Refers:
- https://github.com/JetBrains/intellij-community/pull/2588
- https://youtrack.jetbrains.com/issue/IDEA-334617/Suggest-installing-Azure-plugin-for-users-who-have-Azure-CLI-installed

### CODE REVIEW

**Review by maartenba — APPROVED** [review]

**Comment by rafaelldi** [comment]
I'm afraid that this can make a lot of notification spam

**Comment by maartenba** [comment]
Should we try it?

**Comment by rafaelldi** [comment]
The other thing is that we have broken `az` login. I think it might be confusing. Maybe we should apply this fix in the new version of the plugin?

**Comment by maartenba** [comment]
I think that's more reasonable indeed. @Flanker32, thanks for contributing! Though we may postpone your PR until the new plugin version is ready to go.

**Comment by jreznot** [comment]
> I'm afraid that this can make a lot of notification spam

Since 2023.3 where `az` will be allowed we no longer show notifications for such suggestions, they only appear in Settings - Plugins

**Comment by rafaelldi** [comment]
I've added `az` support in the `develop` branch https://github.com/JetBrains/azure-tools-for-intellij/commit/28880cf08d4c26fc14eaf2a5d18e5a327c6f3b76

**Pull request closed without merging**
