### PR TITLE
Fix #234. Enable Rider C# Backend in Azure plugin

### LINKED ISSUE #234: Enable protocol and backend extensions in plugin
We should enable backend and protocol extension in plugin. This will allow us to:
- Re-write Function gutter mark
- Add completion in forms
- Enable analysis
- etc...

### PR DESCRIPTION
**Pull request by sdubov**
- Add R# backend logic into Azure plugin
- Migrate FunctionApp gutter mark and configuration run/debug logic from frontend to backend
- Bump gradle version to meet rd-gen min requirements
- Bump intellij gradle plugin version to apply fix in dependencies in tests
- Replace Findbug plugin in idea repo that is deprecated in Gradle version 6+ with Spotbugs plugin
- Update gradle script to generate protocol models, compile backend and prepare backend artefacts inside a plugin
- Add logic to patch backend icons on a frontend and replace icon paths with common Azure Functions icons
- Drop Frontend configuration producer and run marker contributors
- Cleanup code

Fixes #234

### CODE REVIEW

**Comment by sdubov** [comment]
@maartenba, please note: this commit requires us to reconfigure Docker image (add `dotnet` SDK installation) that is used for building the backend part. Currently, I've switch it to a custom one deployed to https://hub.docker.com/repository/docker/sdubov/rider-azure-toolkit-image. I've created a separate ticket to correct the infrastructure - #308.

**Review by maartenba — CHANGES_REQUESTED** [review]
Reviewed and tested.

Wondering about the gutter mark...
image

If work in progress, please ignore and consider PR approved :)

**Comment by sdubov** [comment]
@maartenba, do you mean run configuration or shortcuts? Run config works on my end (function is started and I can get output). Could you please provide some more details about the issue with run and debug? Any errors?

`Create new ...` - sure, I will remove it. I was not sure if we need it or not and have decided to make the same ones that Idea contributors provides on a frontend.

**Comment by sdubov** [comment]
Dropped `Create new Function App` from gutter options.

**Review by maartenba — APPROVED** [review]
Seems good now, thanks @sdubov !

**Pull request merged**
