### PR TITLE
Functions: Development: Item templates

### LINKED ISSUE #152: Functions: Development: Item templates
Prerequisites:

* User has Azure Functions Core Tools installed (https://www.npmjs.com/package/azure-functions-core-tools)
* We have `dotnet` tool path available and verified the above was installed

Item templates for functions are available from Azure Functions Core Tools, and are regular `dotnet new` templates.

Location on disk: `%APPDATA%\npm\node_modules\azure-functions-core-tools\bin\templates\itemTemplates.nupkg`

Contents:

image

Should be parsed, and depending on active language in current project: filtered. Similar to https://code.visualstudio.com/tutorials/functions-extension/create-function

### PR DESCRIPTION
**Pull request by maartenba**
Fixes #152 (and the templates part of https://youtrack.jetbrains.com/issue/RIDER-26086)

### CODE REVIEW

**Review by sdubov — APPROVED** [review]

**Comment by 0xced** [comment]
How can I use this in Rider 2019.1 EAP5? When I create a new solution, I don't see any Azure Functions template. Do I have to install something?
Screenshot 2019-04-07 at 10 34 14

**Comment by maartenba** [comment]
@0xced the plugin for 2019.1 has no yet been released, so project/item templates are not yet available.

**Comment by 0xced** [comment]
According to [RIDER-26086](https://youtrack.jetbrains.com/issue/RIDER-26086), it is fixed and available in 2019.1.0 EAP 5. Should I actually wait for the final 2019.1 release?

**Comment by maartenba** [comment]
@0xced The fix there is about the infrastructure that the plugin here needs. Plugin has everything as well, but we're finalizing some things before making a release.

**Comment by 0xced** [comment]
OK, thank you for the clarification.

**Pull request merged**
