### PR TITLE
Managed identity - UX improvements

### PR DESCRIPTION
**Pull request by maartenba**
UX improvements for #204 based on user feedback, now showing the list of subscriptions you can access as well:

image

### CODE REVIEW

**Review by sdubov — CHANGES_REQUESTED** [review]
1. I was confused a bit having "Logout..." option next to "Login" at the same time. 

Screenshot 2020-08-28 at 23 46 56

As far as I understand this is because this page is expected to cover Azure CLI login only from the one handle, and should provide an option to "log out" if you logged in using a different option from the other hand. I found it is not quite clean. What do you think if we have one button at a time. So, we show "Login" with all possible options if a user is not logged in and we show "Logout" for logged in users. If a user use non CLI option - then we show a warning as we do now, otherwise - show a green mark. What do you think?

2. It might be my account type, but I do not see any details when signed in with az.
Screenshot 2020-08-29 at 00 06 51

with the number of errors:
```
[Correlation ID: dd8ce979-d9b3-4800-b7e9-d922578fffd5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2020-05-12T15:24:27.1475948Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2020-08-13T13:38:13.0000000Z'.\r\nTrace ID: 1b50a3c9-961d-4f0b-b54e-08a7ca410400\r\nCorrelation ID: dd8ce979-d9b3-4800-b7e9-d922578fffd5\r\nTimestamp: 2020-08-28 21:06:39Z","error":"invalid_grant","error_uri":"https:\/\/login.microsoftonline.com\/error?code=50173"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:129)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Screenshot 2020-08-28 at 23 48 41

**Comment by maartenba** [comment]
For 1) - good idea! Updated the UI to do this now.
For 2), exception is now being handled.

**Review by sdubov — CHANGES_REQUESTED** [review]
Buttons logic looks good. Thank you!

Several more comments regarding this dialog UX:
1. `Sign in` and `Sign out` buttons are located on a different height between link above and status below

SignIn

SignOut

2. Subscriptions table shows entries only when logged in using Azure CLI. I think it make sense to show it with any login type if we consider this setting page as a common subscription manager. If not. It is ok, but still looks a but confusing when the page is saying that I have no subscriptions, but I have been logged in.

3. Maybe we should indicate an "active subscription" in the subscriptions table? Currently, there is only a list with no indication. E.g. use a green arrow before the subscription name or show an active one in bold.

4. Do you think it might be helpful to have a small copy icons next to the subscription ID and Tenant ID (that e.g. appears on hover) and allow you to copy those values. As a user I see values, but I have no idea how to use them (except of comparing with some subscription ID that I know if needed). This might go to a separate task though :)

**Comment by maartenba** [comment]
1) It's a `LayoutBuilder` issue, but worked around it. Fixed!

2 + 3) Seems the wording needs some changes. The dialog shows you which subscriptions are accessible using managed identity from inside your code. The Azure SDK you use in your application code [transparently uses the Azure CLI credential](https://github.com/Azure/azure-sdk-for-net/blob/f5afa9aa8840f2a14ef47a9dbfe569247d3ffa93/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/AzureCliAccessTokenProvider.cs). Essentially, this dialog is just to make sure that you are logged in with Azure CLI, and show the subscriptions which you will be able to access in application code.

So it does not really have anything to do with what the plugin in Rider can do. Maybe the text above the list should say `Resources in the following subscriptions may be accessible from code:` or something similar?

4) Not super useful I think, the idea for managed identity/service authentication is that the application gets this from Azure CLI under the hood.

**Review by sdubov — APPROVED** [review]
LGTM. I would only add some space between `login status` and `Subscription description above the table`.

SubscriptionTable

**Comment by maartenba** [comment]
Thanks @sdubov !
Added, squashing onto `203` and cherry picking to `202`.

**Pull request merged**
