### PR TITLE
Update Azure dependencies to latest version

### PR DESCRIPTION
**Pull request by maartenba**

### CODE REVIEW

**Comment by maartenba** [comment]
No idea why build for this one is failing :-/

**Comment by maartenba** [comment]
@sdubov Can we merge this one?

**Comment by sdubov** [comment]
@maartenba, we still have red build here. I would investigate prior to merging this into 192. Otherwise, we will have broken build in 192.

**Comment by maartenba** [comment]
Cancelling this PR, will await upstream updates instead.

**Pull request closed without merging**
