### PR TITLE
Fix #310. Migrate Timer Function App trigger cron completion to backend

### LINKED ISSUE #310: Migrate TimerTrigger function app completion logic to backend
Currently, we have a logic for TimerTrigger function app schedule expression on a frontend - `AzureFunctionsTimerTriggerCronInspection`. We need to migrate it to backend when #234 is merged into `202` branch.

Please see notes in #297 from @maartenba.

### PR DESCRIPTION
**Pull request by sdubov**
- Add Backend completion provider for Timer Trigger Function for TimerTrigger attribute
- Add inspection to check Timer Trigger Cron expression
- Add Azure errors definition XML file that is used for generation classes for inspections
- Add reference for NCrontab library that is used for parsing Cron expressions in Rider inspection
- Update backend build gradle scrip
- Update backend assembly names for all projects
- Bump ReferenceAssemblies version to release

### CODE REVIEW

**Comment by sdubov** [comment]
@maartenba, I'm still working on this PR. Currently, R# terminate autopoup for symbols in Cron: `*`, `<space>`, `-`, `,`, `<digit>` in CSharp. Looking into a way to override this behaviour for a particular case.

**Comment by maartenba** [comment]
Let me know when you want me o go through. Did a quick pass and LGTM apart from the autopopup you mentioned.

**Review by maartenba — APPROVED** [review]

**Comment by sdubov** [comment]
I've added a minor update for completion logic that allows to type number prefix in autopopup.

Here are several notes about completion behaviour:
1. Frontend completion contributor behaviour had several limitations for Cron expressions items as well. For example `*` prefix produce no completion options since `*` char is a special symbol in default Idea pattern matching logic. So, when you type `*` there are no matching items found.
Sometimes `*` is not resolved after numbers and close the autopopup. `/` terminates the completion and close the lookup.

2. Prefix matching is processed on a frontend. By default Rider override this for C# language behaviour to stop completion on first digit char. It is described in `ProtocolCompletionContributor`. I'm not sure why it was set up that way for C# completion behaviour (I assume it is because identifiers or types cannot begin with number). Anyway, I've override this behaviour for all completion cases in the plugin to ignore digit prefixes.

3. Rider overrides the prefix matching behaviour to ignore any symbol except digit, `#`, `@` and java identifiers. This logic is described in `CSharpCompletionHelper` class. This differ from Idea prefix matcher behaviour and frontend completion logic to skip most of prefixes. E.g. `0 */5{caret}` - this opens items matching `0 */5` on Idea's matchers, but you are getting all items that match `5` after porting completion to backend and use Rider prefix matchers that are taken in that case. They consider `/` as not acceptable for prefix and proceed with `5`. Overriding this behaviour is behaviour for one particular case is not a trivial task since we do not have PSI on a frontend and cannot define the exact completion case. So, I've decided to leave it as is for now.

**Comment by maartenba** [comment]
Guess we will see once folks start using it. Well done @sdubov - this seems like it was quite the rabbit hole 🤗

**Pull request merged**
