### PR TITLE
Merge upstream release branch into 211 #455

### LINKED ISSUE #455: Merge upstream into 211
Merge upstream `master` into `211`.

This brings:
* https://github.com/microsoft/azure-tools-for-java/releases/tag/azure-intellij-toolkit-v3.47.0
  * Add Azure Database for MySQL support in Azure Toolkits
    * Manage Azure Database for MySQL instance (create/start/stop/restart/configure/show properties)
    * Configure Azure Database for MySQL to allow access it from azure services and local PC
    * Show sample of JDBC connection strings on Azure Database for MySQL
    * Open and connect to Azure Database for MySQL server by Intellij database tools
  * Enable speed search in subscription table
  * Enable speed search in Azure explorer tree
  * Enhance App Service file explorer in Azure explorer

### PR DESCRIPTION
**Pull request by sdubov**
Fixes #455 [WIP]. I've fixed all compilation issues on Utils and Plugin sides. 
Need to:
- Check icons (it was changed a way upstream set icons. Now it is separated for each module. Need to check if we would like to stay with our icons or use original ones that are `*.svg` now)
- Check if some Rider related features are not lost and all existing functionality works
- Test

### CODE REVIEW

**Comment by sdubov** [comment]
There is a massive change in Utils related to node actions and presentation.

**Comment by maartenba** [comment]
Tested and found:

1. When using Azure CLI login, something seems to go wrong on retrieving subscriptions:

image

Might be these:
https://github.com/microsoft/azure-tools-for-java/issues/4977
https://github.com/microsoft/azure-tools-for-java/issues/5053

2. Fixed. ~MySQL node's "show properties" does not seem to do anything.~

3. Fixed. ~Try exploring a storage account, get an Exception:~

```
javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.XMLOutputFactoryBase not found
	at javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)...
```

**Comment by maartenba** [comment]
The Azure CLI issues are known upstream:
https://github.com/microsoft/azure-tools-for-java/issues/4977
https://github.com/microsoft/azure-tools-for-java/issues/5053

**Comment by maartenba** [comment]
Apart from the Azure CLI login issue, branch LGTM

**Review by maartenba — APPROVED** [review]

**Pull request merged**
