### PR TITLE
Fixed RIDER-47863. Fix Gradle configuration to run Rider tests via Gradle task

### PR DESCRIPTION
**Pull request by sdubov**
- Move idea tests related logic and tests into idea module to be able to successfully run them on TeamCity
- Bump versions for 211 release
- Minor updates in configuration

### CODE REVIEW

**Comment by maartenba** [comment]
LGTM, think I can try to rebase my `212` on top

**Review by maartenba — CHANGES_REQUESTED** [review]
LGTM, think I can try to rebase my `212` on top. Build does not seem happy...

**Comment by sdubov** [comment]
@maartenba, I would merge this into 212, then squash all your changes into a single commit and then fix issues with migration PR. How does it sound?

**Comment by maartenba** [comment]
Sounds good!

**Comment by sdubov** [comment]
@maartenba, approve is required for merging ;) plz.

**Review by maartenba — APPROVED** [review]

**Pull request merged**
